//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.dbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialPaper
    {
        public System.Guid KeyFinance { get; set; }
        public string NoFP { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string NoFP2 { get; set; }
        public Nullable<System.DateTime> DAY2 { get; set; }
        public Nullable<int> Quantily { get; set; }
        public Nullable<double> Sum { get; set; }
        public string Note { get; set; }
        public string IdCompany { get; set; }
        public string IdDepartment { get; set; }
        public string IdDepartment2 { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
    }
}
