//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string BARCODE { get; set; }
        public string NameProduct { get; set; }
        public string NameAT { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Price { get; set; }
        public string IdSupplier { get; set; }
        public Nullable<int> IdSource { get; set; }
        public Nullable<int> IdGroupProduct { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public string Image { get; set; }
    }
}
