//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FinancialPaper> FinancialPapers { get; set; }
        public virtual DbSet<FinancialPaperDetail> FinancialPaperDetails { get; set; }
        public virtual DbSet<GroupProduct> GroupProducts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SYS_FUNC> SYS_FUNC { get; set; }
        public virtual DbSet<SYS_SEQUENCE> SYS_SEQUENCE { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    
        [DbFunction("Entities", "FN_TURNOVER_MONTHLY")]
        public virtual IQueryable<FN_TURNOVER_MONTHLY_Result> FN_TURNOVER_MONTHLY(Nullable<System.DateTime> dATE1, Nullable<System.DateTime> dATE2)
        {
            var dATE1Parameter = dATE1.HasValue ?
                new ObjectParameter("DATE1", dATE1) :
                new ObjectParameter("DATE1", typeof(System.DateTime));
    
            var dATE2Parameter = dATE2.HasValue ?
                new ObjectParameter("DATE2", dATE2) :
                new ObjectParameter("DATE2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_TURNOVER_MONTHLY_Result>("[Entities].[FN_TURNOVER_MONTHLY](@DATE1, @DATE2)", dATE1Parameter, dATE2Parameter);
        }
    }
}
