//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string IdDepartment { get; set; }
        public string NameDepartment { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string IdCompany { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public string Syntax { get; set; }
        public Nullable<bool> STOCK { get; set; }
    }
}
